ZevConfigDto:
  type: object
  properties:
    id:
      $ref: '../schemas/commons.yaml#/Id'
    name:
      type: string
    street:
      type: string
    houseNr:
      type: string
    postalCode:
      type: string
    city:
      type: string
    propertyNr:
      type: string

ModifiableZevConfigDto:
  type: object
  properties:
    name:
      type: string
    street:
      type: string
    houseNr:
      type: string
    postalCode:
      type: string
    city:
      type: string
    propertyNr:
      type: string
  required:
    - street
    - houseNr
    - postalCode
    - city

ZevRepresentativeConfigDto:
  type: object
  properties:
    id:
      $ref: '../schemas/commons.yaml#/Id'
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
      format: email
    street:
      type: string
    houseNr:
      type: string
    postalCode:
      type: string
    city:
      type: string
    phoneNr:
      type: string
    mobileNr:
      type: string

ModifiableZevRepresentativeConfigDto:
  type: object
  properties:
    firstName:
      type: string
    lastName:
      type: string
    email:
      type: string
      format: email
    street:
      type: string
    houseNr:
      type: string
    postalCode:
      type: string
    city:
      type: string
    phoneNr:
      type: string
    mobileNr:
      type: string
  required:
    - firstName
    - lastName
    - email
    - street
    - houseNr
    - postalCode
    - city
    - phoneNr
    - mobileNr