---
services:
  # frontend:
  #   build: 
  #     context: frontend
  #   ports:
  #   - 18001:3000
  #   depends_on:
  #   - backend
  
  # nginx:
  #   build:
  #     context: nginx
  #   ports:
  #   - 18000:80

  backend:
    build:
      context: backend
    ports:
      - 18002:8001
    env_file:
      - backend.env
    depends_on:
      - database

  database:
    image: postgres
    user: postgres
    environment:
      POSTGRES_DB: openzev
      POSTGRES_USER: openzev
      POSTGRES_PASSWORD: password
    ports:
      - 18003:5432
    volumes:
      - openzev-data:/var/lib/postgresql/data

volumes:
  openzev-data:
