/**
 * OpenZEV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeterPointDto } from './meterPointDto';


export interface ReadingDto { 
    id: string;
    meterPoint?: MeterPointDto;
    date: string;
    peakTariff: number;
    offPeakTariff: number;
    total: number;
}

