get:
  operationId: getZevConfig
  tags:
    - Config
  responses:
    '200':
      description: Settings for ZEV
      content:
        application/json:
          schema:
            $ref: '../schemas/configs.yaml#/ZevConfigDto'
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '../schemas/commons.yaml#/ErrorDto'
put:
  operationId: saveZevConfig
  tags:
    - Config
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/configs.yaml#/ModifiableZevConfigDto'
  responses:
    '200':
      description: Saved
      content:
        application/json:
          schema:
            $ref: '../schemas/commons.yaml#/Id'
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '../schemas/commons.yaml#/ErrorDto'