put:
  operationId: resetPassword
  tags:
    - User
  parameters:
    - $ref: '../parameters/users.yaml#/UserParam'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/users.yaml#/ModifiablePasswordResetDto'
  responses:
    '200':
      description: Saved
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '../schemas/commons.yaml#/ErrorDto'
