server:
  port: 8001

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: /db/changelog/main.xml
  mail.properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

openzev:
  ckw:
    base-url: https://etility.ckw.ch/etility/proxy/ckw/serviceAzureDA/smartmeter/
  qr-generator:
    base-url: https://api.raiffeisen.ch/qrgenerator/v1/
