spring:
  datasource:
    url: jdbc:postgresql://localhost:18003/openzev
    username: openzev
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.ethereal.email
    port: 587
    username: matteo66@ethereal.email
    password: 8J8EYDM6xKTYjpfhpJ
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

    