openapi: 3.1.1

info:
  version: 1.0.0
  title: OpenZEV API

paths:
  /v1/consumptions:
    get:
      operationId: getConsumptions
      tags:
        - Consumptions
      parameters:
        - name: meterPointId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: All consumptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consumption'

    post:
      operationId: createConsumption
      tags:
        - Consumptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consumption'
      responses:
        201:
          description: Consumption created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumption'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/consumptions/{consumptionId}:
    parameters:
      - $ref: '#/components/parameters/ConsumptionId'

    get:
      operationId: getConsumption
      tags:
        - Consumptions
      responses:
        200:
          description: Detail of consumption
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumption'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: changeConsumption
      tags:
        - Consumptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consumption'
      responses:
        200:
          description: Consumption changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumption'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteConsumption
      tags:
        - Consumptions
      responses:
        204:
          description: Consumption deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/meter-points:
    get:
      operationId: getMeterPoints
      tags:
        - Meter Point
      responses:
        200:
          description: All meter points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MeterPoint'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      operationId: createMeterPoint
      tags:
        - Meter Point
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterPoint'
      responses:
        201:
          description: Created meter point
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterPoint'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/meter-points/{meterPointId}:
    parameters:
      - $ref: '#/components/parameters/MeterPointId'

    get:
      operationId: getMeterPoint
      tags:
        - Meter Point
      responses:
        200:
          description: Detail meter point
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterPoint'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: changeMeterPoint
      tags:
        - Meter Point
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterPoint'
      responses:
        200:
          description: Changed meter point
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterPoint'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteMeterPoint
      tags:
        - Meter Point
      responses:
        204:
          description: Deleted meter point
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/units:
    get:
      operationId: getUnits
      tags:
        - Unit
      responses:
        200:
          description: All units
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unit'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      operationId: createUnit
      tags:
        - Unit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        201:
          description: Created unit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/units/{unitId}:
    parameters:
      - $ref: '#/components/parameters/UnitId'

    get:
      operationId: getUnit
      tags:
        - Unit
      responses:
        200:
          description: Detail unit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: changeUnit
      tags:
        - Unit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        200:
          description: Changed unit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteUnit
      tags:
        - Unit
      responses:
        204:
          description: Deleted unit
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/vendor-invoices:

    get:
      operationId: getVendorInvoices
      tags:
        - Vendor Invoices
      responses:
        200:
          description: All vendor invoices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VendorInvoice'

    post:
      operationId: createVendorInvoice
      tags:
        - Vendor Invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorInvoice'
      responses:
        201:
          description: Vendor invoice created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorInvoice'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/vendor-invoices/{vendorInvoiceId}:
    parameters:
      - $ref: '#/components/parameters/VendorInvoiceId'

    get:
      operationId: getVendorInvoice
      tags:
        - Vendor Invoices
      responses:
        200:
          description: Detail of vendor invoice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorInvoice'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: changeVendorInvoice
      tags:
        - Vendor Invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorInvoice'
      responses:
        200:
          description: Vendo invoice changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorInvoice'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteVendorInvoice
      tags:
        - Vendor Invoices
      responses:
        204:
          description: Vendor invoice deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/vendor-invoices/{vendorInvoiceId}/items:
    parameters:
      - $ref: '#/components/parameters/VendorInvoiceId'

    get:
      operationId: getVendorInvoiceItems
      tags:
        - Vendor Invoice Items
      responses:
        200:
          description: All vendor invoice items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VendorInvoiceItem'

    post:
      operationId: createVendorInvoiceItem
      tags:
        - Vendor Invoice Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorInvoiceItem'
      responses:
        201:
          description: Vendor invoice item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorInvoiceItem'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/vendor-invoices/{vendorInvoiceId}/items/{vendorInvoiceItemId}:
    parameters:
      - $ref: '#/components/parameters/VendorInvoiceId'
      - $ref: '#/components/parameters/VendorInvoiceItemId'

    put:
      operationId: changeVendorInvoiceItem
      tags:
        - Vendor Invoice Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorInvoiceItem'
      responses:
        200:
          description: Vendo invoice item changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorInvoiceItem'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deleteVendorInvoiceItem
      tags:
        - Vendor Invoice Items
      responses:
        204:
          description: Vendor invoice item deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    VendorInvoiceId:
      name: vendorInvoiceId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
      required: true

    VendorInvoiceItemId:
      name: vendorInvoiceItemId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
      required: true

    ConsumptionId:
      name: consumptionId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
      required: true

    MeterPointId:
      name: meterPointId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
      required: true

    UnitId:
      name: unitId
      in: path
      schema:
        $ref: '#/components/schemas/Id'
      required: true

  schemas:
    Id:
      type: string
      format: uuid

    Date:
      type: string
      format: date

    DateTime:
      type: string
      format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        args:
          type: array
          items:
            type: string
        message:
          type: string
      required:
        - code
        - message

    Consumption:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
          readOnly: true
        meterPoint:
          $ref: '#/components/schemas/MeterPoint'
          readOnly: true
        meterPointId:
          $ref: '#/components/schemas/Id'
          writeOnly: true
        previousConsumption:
          $ref: '#/components/schemas/Consumption'
          readOnly: true
        previousConsumptionId:
          $ref: '#/components/schemas/Id'
          writeOnly: true
        date:
          $ref: '#/components/schemas/Date'
        total:
          type: number
      required:
        - date
        - meterPointId
        - total

    VendorInvoice:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
          readOnly: true
        state:
          type: string
          enum: [ OPEN, IN_PROGRESS, DONE ]
        date:
          $ref: '#/components/schemas/Date'
        periodFrom:
          $ref: '#/components/schemas/Date'
        periodUpto:
          $ref: '#/components/schemas/Date'
        dueDate:
          $ref: '#/components/schemas/Date'
      required:
        - date
        - dueDate

    VendorInvoiceItem:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
          readOnly: true
        type:
          type: string
          enum: [ CHARGE, CREDIT ]
        position:
          type: integer
        name:
          type: string
        description:
          type: string
        quantity:
          type: number
          format: float
        unit:
          oneOf:
            - type: string
              enum: [ '%', kW, kWh, MONTHS ]
            - type: string
          type: string
        price:
          type: number
          format: float
        total:
          type: number
          format: float
      required:
        - name
        - quantity
        - unit
        - price
        - total

    MeterPoint:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
          readOnly: true
        unitId:
          $ref: '#/components/schemas/Id'
          writeOnly: true
        unit:
          $ref: '#/components/schemas/Unit'
          readOnly: true
        number:
          type: string
      required:
        - unitId
        - number

    Unit:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
          readOnly: true
        number:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - number
        - lastName