openapi: '3.0.0'
info:
  version: 1.0.0
  title: OpenZEV API

paths:
  /v1/settings/bank-accounts:
    $ref: './paths/v1-settings-bank-accounts.yaml'

  /v1/settings/bank-accounts/{bankAccountId}:
    $ref: './paths/v1-settings-bank-accounts-id.yaml'

  /v1/settings:
    $ref: './paths/v1-settings.yaml'

  /v1/settings/representatives:
    $ref: './paths/v1-settings-representatives.yaml'

  /v1/settings/representatives/{representativeId}:
    $ref: './paths/v1-settings-representatives-id.yaml'

  /v1/documents/{documentId}:
    $ref: './paths/v1-documents-id.yaml'

  /v1/invoices:
    $ref: './paths/v1-invoices.yaml'

  /v1/invoices/{invoiceId}:
    $ref: './paths/v1-invoices-id.yaml'

  /v1/invoices/{invoiceId}/items:
    $ref: './paths/v1-invoices-id-items.yaml'

  /v1/invoices/{invoiceId}/payments:
    $ref: './paths/v1-invoices-id-payments.yaml'

  /v1/invoices/{invoiceId}/pdf:
    $ref: './paths/v1-invoices-id-pdf.yaml'

  /v1/items/{itemId}:
    $ref: './paths/v1-items-id.yaml'

  /v1/owners:
    $ref: './paths/v1-owners.yaml'

  /v1/owners/{ownerId}:
    $ref: './paths/v1-owners-id.yaml'

  /v1/payments/{paymentId}:
    $ref: './paths/v1-payments-id.yaml'

  /v1/products:
    $ref: './paths/v1-products.yaml'

  /v1/products/{productId}:
    $ref: './paths/v1-products-id.yaml'

  /v1/units:
    $ref: './paths/v1-units.yaml'

  /v1/units/{unitId}:
    $ref: './paths/v1-units-id.yaml'

  /v1/units/{unitId}/ownerships:
    $ref: './paths/v1-units-id-ownerships.yaml'

  /v1/ownerships/{ownershipId}:
    $ref: './paths/v1-ownerships-id.yaml'
